### PR TITLE
Test inspired by https://github.com/Perl/perl5/issues/17903

### PR DESCRIPTION
**Pull request by ribasushi**
Does not fail for me locally, but pushing the written code just in case

cc @haarg @leonerd there should be a way to make this fail based on the  #p5p conversation form Jun 27, but nothing took.

### CODE REVIEW

**Comment by leonerd** [comment]
Yeah; it's weird. All my attempts to make it fail in small test cases have failed-to-fail as well. The only failing case I have is the huge test of Object::Pad - whose .xs file is over 2k lines long. Hardly counts as minimal ;)

I may have to start from there and just hack large chunks off it until I have something smaller to demonstrate the bug.

**Comment by leonerd** [comment]
The more I think about it the more I think you cannot provoke this bug from Perl code, because of the way nested runloops work. The `croak()` has to be in XS, not Perl.

**Comment by ribasushi** [comment]
@haarg this is still worth merging afaict

**Comment by ribasushi** [comment]
> this is still worth merging afaict

or not 🤷

**Comment by karenetheridge** [comment]
I can't merge something without some reviews, because I'm not interested in getting yelled at for breaking cpan. :)

if @haarg or @leonerd or @leont want to take a look that's great :)

**Pull request closed without merging**
