### PR TITLE
Misc

### PR DESCRIPTION
**Pull request by ribasushi**
@haarg this is an expansion/fix of your test from way back. Please review when time permits.

### CODE REVIEW

**Comment by karenetheridge** [comment]
I turned on Travis testing for this repository but hadn't pushed a config file yet -- I've done so now in the 'topic/travis' branch. If the run passes there I will merge that to master so you can rebase to it for a passing test here (turnaround time seems to be a few hours for full tests, these days).

**Comment by ribasushi** [comment]
@haarg adjusted the last commit slightly ( mainly better docs ), as `$^H |= 0x020000` does nothing on 5.6.
Things still work satisfactory on my end

**Comment by karenetheridge** [comment]
thanks, I'll be releasing this as -TRIAL today. Feel free to poke me again next week for a real release as it don't expect any surprises.

**Comment by karenetheridge** [comment]
by the way, you missed a 'Changes' entry -- would you care to write one that describes the changes at a high level?

**Comment by ribasushi** [comment]
The `Changes` you added is fine as-is. However you did unilaterally remove parts of the code you merged. Opened https://github.com/karenetheridge/B-Hooks-EndOfScope/pull/7 to correct this.

**Pull request merged**
